import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Leaf, Scale, CheckSquare, ShieldCheck, AlertOctagon, HelpCircle } from 'lucide-react'

function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 font-sans transition-colors duration-300">
      <div className="max-w-3xl mx-auto space-y-8">
        
        {/* Header toolbar */}
        <div className="flex justify-between items-center pb-6 border-b border-slate-200 dark:border-slate-850">
          <div className="flex items-center space-x-2.5">
            <Leaf className="text-emerald-500" size={24} />
            <span className="font-mono text-lg font-black uppercase tracking-widest text-slate-800 dark:text-white">GreenCo</span>
          </div>
          <button
            onClick={() => navigate('/login')}
            className="inline-flex items-center gap-1.5 px-4 py-2 border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-900 rounded-xl text-xs font-bold text-slate-650 dark:text-slate-400 transition-all cursor-pointer"
          >
            <ArrowLeft size={14} />
            Back to Login
          </button>
        </div>

        {/* Title */}
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-black text-slate-800 dark:text-white tracking-tight">Terms &amp; Conditions</h1>
          <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">Last updated: July 2026</p>
        </div>

        {/* Terms Content Cards */}
        <div className="space-y-6">
          
          <div className="bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800/40 rounded-2xl p-6 shadow-sm space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
              <Scale size={18} />
              <h3 className="font-bold text-sm uppercase tracking-wider">1. Terms of Service</h3>
            </div>
            <p className="text-xs text-slate-650 dark:text-slate-400 leading-relaxed font-medium">
              By registering an enterprise account and accessing the GreenCo Sustainability Intelligence Platform, you agree to comply with and be bound by the following Terms &amp; Conditions.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800/40 rounded-2xl p-6 shadow-sm space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
              <CheckSquare size={18} />
              <h3 className="font-bold text-sm uppercase tracking-wider">2. Acceptable Use &amp; Accuracy</h3>
            </div>
            <p className="text-xs text-slate-650 dark:text-slate-400 leading-relaxed font-medium">
              Organizations must supply accurate, verifiable sustainability metrics, factory baselines, and resource utilization details. GreenCo auditors reserve the right to cross-examine uploaded documentation, trigger site audits, or suspend accounts submitting fraudulent reporting logs.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800/40 rounded-2xl p-6 shadow-sm space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
              <ShieldCheck size={18} />
              <h3 className="font-bold text-sm uppercase tracking-wider">3. Digital Certificate Usage</h3>
            </div>
            <p className="text-xs text-slate-650 dark:text-slate-400 leading-relaxed font-medium">
              Certificates (Bronze, Silver, Gold, Platinum) generated by the GreenCo platform are property of CII Green Business Centre and are issued based on verified score assessments. Organizations are granted a non-exclusive license to display these compliance achievements.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800/40 rounded-2xl p-6 shadow-sm space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
              <AlertOctagon size={18} />
              <h3 className="font-bold text-sm uppercase tracking-wider">4. Account Suspension &amp; Liability</h3>
            </div>
            <p className="text-xs text-slate-650 dark:text-slate-400 leading-relaxed font-medium">
              GreenCo reserves the right to suspend or deactivate company operator privileges in the event of RBAC permissions abuse, security bypass attempts, or payment defaults. GreenCo is not liable for operational errors resulting from incorrect ESG suggestions or copilot recommendations.
            </p>
          </div>

          <div className="bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800/40 rounded-2xl p-6 shadow-sm space-y-3">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
              <HelpCircle size={18} />
              <h3 className="font-bold text-sm uppercase tracking-wider">5. Governing Law</h3>
            </div>
            <p className="text-xs text-slate-650 dark:text-slate-400 leading-relaxed font-medium">
              These terms are governed by and construed in accordance with the laws of India. Any legal disputes arising from platform usage fall under the exclusive jurisdiction of the courts of Hyderabad, Telangana.
            </p>
          </div>

        </div>

        {/* Footer */}
        <div className="text-center text-[10px] text-slate-400 font-bold uppercase tracking-wider pt-6">
          © 2025 GreenCo Sustainability Platform | CII Green Business Centre
        </div>

      </div>
    </div>
  )
}

export default TermsPage
